### ISSUE TITLE
Check-In Rate limiting has potential to block submission even on next day

### ISSUE THREAD

**Issue by dennisgove** [project-vagabond/covid-green-app#104]
The `check-in` flow allows a user to submit a daily checkin. However the app and backend API don't apply the same rate limiting logic and as such the App may allow a user to submit a checkin that the backend API will reject.

Both the App and Backend API rate limit on the _date of checkin_, meaning that if I checkin on Monday then I am allowed to checkin again on Tuesday. However, the App stores the local date of the user while the backend API stores the UTC date. These charts shows what is stored where and when the problem will appear.

| Checkin Time (user local EST) | Checkin Date in App | Checkin Date in Backend |
| --- | --- | --- |
| Monday 5p | Monday | Monday |
| Monday 9p | Monday | Tuesday |

| Initial Checkin | Next Checkin | App Allowed | Backend Allowed | Expected Behavior | Why |
| --- | --- | --- | --- | --- | --- |
| Monday 5p | Monday 6p | No | No | Yes | |
| Monday 5p | Tuesday 1a | Yes | Yes | Yes | |
| Monday 9p | Tuesday 1a | Yes | No | No | DB stores checkin date of Tuesday |
| Monday 9p | Tuesday 5p | Yes | No | No | | DB stores checkin date of Tuesday |
| Monday 9p | Tuesday 9p | Yes | Yes | Yes | |

Relevant Links:
* App
   * https://github.com/project-vagabond/covid-green-app/blob/nys/src/providers/context.tsx#L171
   * https://github.com/project-vagabond/covid-green-app/blob/nys/src/providers/context.tsx#L335
   * https://github.com/project-vagabond/covid-green-app/blob/nys/src/providers/context.tsx#L312
* Backend API
   * https://github.com/project-vagabond/covid-green-backend-api/blob/nys/lib/routes/check-in/index.js#L27-L33
   * https://github.com/project-vagabond/covid-green-backend-api/blob/nys/lib/routes/check-in/query.js#L14-L15

**Comment by dennisgove** [comment]
@fiacc @colmharte @fahd-arshad @floridemai for visibility. It appears I'm not able to assign people to this.

**Comment by kevin-sheldon** [comment]
I see that #162 was closed. Is this the same issue? If so, can we close?

**Comment by AlanSl** [comment]
@kevin-sheldon They're not the same issue. 

My understanding is that the "Critical" side of this has been addressed in other issues, but there is still a little ongoing server side work specific to this issue, ensuring that the server-side validation is perfectly in sync.

**Comment by AlanSl** [comment]
@colmharte has confirmed that enough has been done on the backend here that we can indeed downgrade the priority. There's still a little to do but it's no longer critical.

**Comment by dennisgove** [comment]
This is fine to downgrade the priority. The backend API now allows taking the PHA timezone into account. It's not perfect but for most regions will be close enough.
