### ISSUE TITLE
Retry with a delay on HTTP status 429

### ISSUE THREAD

**Issue by segfault** [project-vagabond/covid-green-app#331]
The server API gateway will throttle requests by sending HTTP 429 "too many requests". The app should retry at least once if it encounters this response. This should prevent any users from encountering burst load related failures.

**Comment by segfault** [comment]
Hopefully something like https://www.npmjs.com/package/fetch-retry would work in concert with the react-native certificate pinning library.

**Comment by dgonzalez** [comment]
looping @colmharte .

**Comment by colmharte** [comment]
Where we respond with 429s to app its in places we would not want an auto retry. I would not change client at this stage.

**Comment by segfault** [comment]
All calls go through the API gateway which will respond with 429s to indicate to a client that it should retry per AWS. This is separate from the backend-api's usage of 429s which I believe is selective. We asking for a big limit but their guidance to us is to honor the 429s. In our tests we've seen this from all routes due to the API gateway.

**Comment by colmharte** [comment]
at what volume of traffic are you seeing 429 responses from api gateway?

**Comment by segfault** [comment]
It's a large level of traffic. 10k requests per second, but that's across all requests to any endpoint fronted by the API gateway. As we approach 10k requests per second we start seeing 5-20% of the requests come back with 429s from the API gateway.

The only endpoint I'd be concerned about is the initial registration, if that fails gracefully in some way then I think we're covered.

**Comment by colmharte** [comment]
In the app the user can just press the Yes button a second time to reinitiate register so would think we are covered on this.
